# Generated by Django 2.0 on 2018-01-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcrontab', '0004_auto_20180105_1739'),
        ('crontab_formal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crontab_formal.ServerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PyScriptBaseInfoNew',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.DateField()),
                ('name', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('function', models.CharField(max_length=50, verbose_name='程序功能')),
                ('exec_plan', models.IntegerField(blank=True, choices=[(1, 'day'), (2, 'month'), (3, 'quarter')], null=True, verbose_name='执行计划')),
                ('exec_month', models.IntegerField(blank=True, null=True)),
                ('exec_day', models.IntegerField(blank=True, null=True)),
                ('exec_time', models.CharField(blank=True, max_length=50, null=True)),
                ('is_stop', models.IntegerField(choices=[(0, '执行'), (1, '停止')], default=0)),
                ('deploy_directory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crontab_formal.Path')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='rcrontab.PyScriptOwnerList')),
            ],
        ),
        migrations.CreateModel(
            name='TablesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_server', models.CharField(max_length=20)),
                ('db_name', models.CharField(max_length=30)),
                ('table_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pyscriptbaseinfonew',
            name='pre_tables',
            field=models.ManyToManyField(related_name='son_program', to='crontab_formal.TablesInfo'),
        ),
        migrations.AddField(
            model_name='pyscriptbaseinfonew',
            name='result_tables',
            field=models.ManyToManyField(related_name='father_program', to='crontab_formal.TablesInfo'),
        ),
    ]
