# Generated by Django 2.0 on 2018-01-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultlog',
            name='script',
        ),
        migrations.DeleteModel(
            name='ResultLog',
        ),
    ]
