# Generated by Django 2.0 on 2018-01-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0002_auto_20180123_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateField()),
                ('event_time', models.DateTimeField()),
                ('event_type', models.IntegerField(choices=[(0, '执行调度'), (1, '开始执行'), (2, '正常结束'), (3, '异常终止')])),
                ('err_info', models.CharField(blank=True, max_length=255, null=True)),
                ('script', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='crontab_formal.PyScriptBaseInfoV2')),
            ],
            options={
                'db_table': 'py_script_result_log',
            },
        ),
    ]
