# Generated by Django 2.0 on 2018-01-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0003_resultlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultlog',
            name='subversion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
