# Generated by Django 2.0 on 2018-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0005_auto_20180124_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyscriptbaseinfov2',
            name='times',
            field=models.IntegerField(default=1),
        ),
    ]
