# Generated by Django 2.0 on 2018-01-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0006_pyscriptbaseinfov2_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultlog',
            old_name='err_info',
            new_name='extra_info',
        ),
    ]
