# Generated by Django 2.0 on 2018-01-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0007_auto_20180125_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultlog',
            name='tag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
