# Generated by Django 2.0 on 2018-01-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0008_resultlog_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyScriptBaseExtraInfoV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_way', models.IntegerField(choices=[(0, 'ignore'), (1, 'replace')])),
                ('sid', models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_info', to='crontab_formal.PyScriptBaseInfoV2')),
            ],
        ),
    ]
