# Generated by Django 2.0 on 2018-01-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_formal', '0009_pyscriptbaseextrainfov2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultlog',
            old_name='tag',
            new_name='flag',
        ),
    ]
